---
title: "NB Fake News Jari Cuijpers"
author:
  - Jari Cuijpers - Author
  - name Reviewer here - Reviewer
date: 23-3-2022
output:
   html_notebook:
    toc: true
    toc_depth: 2
---

```{r}
library(tidyverse)
library(tm)
library(caret)
library(wordcloud)
library(e1071)
library(dplyr)
library(SnowballC)
```

##Business understanding
##Create a model for identfiying fake news

##Data understanding

```{r}
url <- "https://raw.githubusercontent.com/HAN-M3DM-Data-Mining/data-mining-s2y2122-jaricuijpers/master/datasets/NB-fakenews.csv"
rawDF <- read.csv (url)
rawDF<- rawDF[-c(1:15000),]
head (rawDF)
str (rawDF)
```

```{r}
rawDF <- mutate(rawDF, label = recode(label,"0"= "real", "1"= "fake"))
rawDF$label <- rawDF$label %>% factor %>% relevel("fake")
class(rawDF$label)
head(rawDF)
```

```{r}
fake <- rawDF %>% filter(label == "fake")
real <- rawDF %>% filter(label == "real")

wordcloud (fake$text, max.words = 20, scale = c(4, 0.8), colors= c("indianred1","indianred2","indianred3","indianred"))
wordcloud (real$text, max.words = 20, scale = c(4, 0.8), colors= c("lightsteelblue1","lightsteelblue2","lightsteelblue3","lightsteelblue"))
```

##Data preperation

```{r}
rawCorpus <- Corpus(VectorSource(rawDF$text))
inspect(rawCorpus[1:3])
```

```{r}
cleanCorpus <- rawCorpus %>% tm_map(tolower) %>% tm_map(removeNumbers)

cleanCorpus <- cleanCorpus %>% tm_map(tolower) %>% tm_map(removeWords, stopwords()) %>% tm_map(removePunctuation)

cleanCorpus <- cleanCorpus %>% tm_map(stripWhitespace)

cleanCorpus <- cleanCorpus %>% tm_map(stemDocument)
```

```{r}
tibble(Raw = rawCorpus$content[1:3], Clean = cleanCorpus$content[1:3])
```

```{r}
cleanDTM <- cleanCorpus %>% DocumentTermMatrix
inspect(cleanDTM)
```

```{r}
trainIndex <- createDataPartition(rawDF$label, p = .75, list = FALSE, times = 1)
head(trainIndex)
```

```{r}
trainDF <- rawDF[trainIndex, ]
testDF <- rawDF[-trainIndex, ]

trainCorpus <- cleanCorpus[trainIndex]
testCorpus <- cleanCorpus[-trainIndex]

trainDTM <- cleanDTM[trainIndex, ]
testDTM <- cleanDTM[-trainIndex, ]

freqWords <- trainDTM %>% findFreqTerms(5)
trainDTM <-  DocumentTermMatrix(trainCorpus, list(dictionary = freqWords))
testDTM <-  DocumentTermMatrix(testCorpus, list(dictionary = freqWords))
```

```{r}
convert_counts <- function(x) {
  x <- ifelse(x > 0, 1, 0) %>% factor(levels = c(0,1), labels = c("No", "Yes"))
}

nColsDTM <- dim(trainDTM)[2]
trainDTM <- apply(trainDTM, MARGIN = 2, convert_counts)
testDTM <- apply(testDTM, MARGIN = 2, convert_counts)

head(trainDTM[,1:10])
```

##Modeling 

```{r}
nbayesModel <- naiveBayes(trainDTM, trainDF$text, laplace = 1)
predVec <- predict(nbayesModel, testDTM)
confusionMatrix(predVec,testDF$label, positive = "fake", dnn = c("Prediction", "True"))
```
##Evaluation
